version: '3'
services:
  dev3:
    container_name: dev3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2203:22"
    hostname: dev3
    volumes:
      - ${SHARED_VOLUME_HOME}:/home/ubuntu/purple/
    command: /opt/docker-internal.sh $
    stdin_open: true
    tty: true
              
    privileged: true
    networks:
      SSID1:
        ipv4_address: 10.10.5.2
  dev2:
    container_name: dev2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2202:22"
    hostname: dev2
    volumes:
      - ${SHARED_VOLUME_HOME}:/home/ubuntu/purple/
    command: /opt/docker-internal.sh $
    depends_on:
      - dev3
    stdin_open: true
    tty: true
              
    privileged: true
    networks:
      SSID1:
        ipv4_address: 10.10.5.3
  dev1:
    container_name: dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2201:22"
    hostname: dev1
    volumes:
      - ${SHARED_VOLUME_HOME}:/home/ubuntu/purple/
    command: /opt/docker-internal.sh $
    depends_on:
      - dev2
    stdin_open: true
    tty: true
              
    privileged: true
    networks:
      SSID1:
        ipv4_address: 10.10.5.4
networks:
  SSID1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.5.0/24
