# ^^^^^^^^^^^^^^^^^^^^^^^^
# ubuntu Dockerfile
FROM ubuntu

RUN apt update && apt install  openssh-server sudo sshpass tcpdump vim tmux tmuxinator net-tools -y
RUN echo 'root:password' | chpasswd
RUN passwd -d root
RUN service ssh start
RUN mkdir ~/.ssh
RUN chmod 700 ~/.ssh
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
RUN sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/g' /etc/ssh/sshd_config
RUN echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config
RUN touch ~/.ssh/authorized_keys
COPY config /root/.ssh/
COPY commands.sh /usr/local/sbin
RUN export EDITOR=vim
RUN sudo tmuxinator new ssid
# RUN mkdir -p ~/.config/
# RUN mkdir -p ~/.config/tmuxinator/
# RUN rm ~/.config/tmuxinator/ssid.yml
SHELL ["/bin/bash", "-c"] 

# RUN cp ssid.yml ~/.config/tmuxinator/ssid.yml
# COPY ssid.yml ~/.config/tmuxinator/
COPY ssid.yml /usr/local/sbin/


# RUN chmod 700 ~/.config/tmuxinator/ssid.yml

# RUN tmuxinator new ssid
RUN chmod +x /usr/local/sbin/commands.sh
RUN chmod 600 ~/.ssh/config

RUN service ssh restart

COPY tcpconf.sh /usr/local/sbin/
RUN chmod +x /usr/local/sbin/tcpconf.sh
RUN echo 'test' > password.txt | chmod 600 password.txt
EXPOSE 22

CMD ["/usr/local/sbin/tcpconf.sh"]


# commands to enter to activate:
# create the containers
    # docker build -t <imagetype> .
    # docker build -t ubuntu .

    # docker run -dit --name <given name> -p <hostport>:<containerport> <image type>
    # docker run -dit --name ssid-dev3 -p 2003:22 ubuntu


# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# alpline Dockerfile 


# RUN \
#   apk update && \
#   apk add openrc --no-cache && \
#   apk add openssh-server && \
#   rc-update add sshd && \
#   rc-status && \
#   touch /run/openrc/softlevel 

# Expose port for ssh
# EXPOSE 22

# Start SSH Service
# CMD ["sh" , "-c", "service sshd restart && sh"]
# RUN mkdir hi