version: '3.9'

services:
  # host/victim container
  dev1:
    container_name: dev-1
    # image: ubuntu
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    ports:
      - "2201:22"
    hostname: dev1
    volumes:
      - /Users/annika/Documents/SSID:/purple/dev1

  dev2:
    container_name: dev-2
    # image: ubuntu
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    ports:
      - "2202:22"
    hostname: dev2
    volumes:
      - /Users/annika/Documents/SSID:/purple/dev2
    depends_on:
      - dev1


  dev3:
    container_name: dev-3
    # image: ubuntu
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    ports:
      - "2203:22"
    hostname: dev3
    volumes:
      - /Users/annika/Documents/SSID:/purple/dev3
    depends_on:
      - dev2

  # hacker container
  dev4:
    container_name: dev-4
    
    # image: ubuntu
    build:
      dockerfile: Dockerfile-ubuntu
    ports:
      - "2204:22"
    hostname: dev4
    volumes:
      - /Users/annika/Documents/SSID:/purple/dev4
    depends_on:
      - dev3

  # tcpdump:
  #   image: kaazing/tcpdump
  #   network_mode: "SSID1"
  #   volumes:
  #     - ./tcpdump:/tcpdump

networks:
  default:
    name: SSID1
    external: true

# networks:
#   external:
#     name: SSID1
  # frontend-network:
  #   # external: true
  #   driver: bridge
  #   external: true
  #   name: SSID1

