version: '3.9'

services:
  # host/victim container
  dev1:
    container_name: dev-1
    # image: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2201:22"
    hostname: dev1
    volumes:
      - ${SHARED_VOLUME}:/purple/
    tty: true

    # command: sleep 1000


  dev2:
    container_name: dev-2
    # image: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2202:22"
    hostname: dev2
    volumes:
      - ${SHARED_VOLUME}:/purple/
    depends_on:
      - dev1
    command: sleep 50


  dev3:
    container_name: dev-3
    # image: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2233:22"
    hostname: dev3
    volumes:
      - ${SHARED_VOLUME}:/purple/
    depends_on:
      - dev2
    command: sleep 50


  # hacker container
  dev4:
    container_name: dev-4
    # image: ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2204:22"
    hostname: dev4
    volumes:
      - ${SHARED_VOLUME}:/purple/
    depends_on:
      - dev3
    command: sleep 50


networks:
  default:
    name: SSID1
    external: true
