version: '3'
services:
  dev4:
    container_name: dev4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2201:22"
    hostname: dev4
    volumes:
      - /home/nate/SSID:/purple/
    command: /opt/docker-internal.sh 2 100
              
  dev3:
    container_name: dev3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2202:22"
    hostname: dev3
    volumes:
      - /home/nate/SSID:/purple/
    command: /opt/docker-internal.sh 2 100
    depends_on:
      - dev4
              
  dev2:
    container_name: dev2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2203:22"
    hostname: dev2
    volumes:
      - /home/nate/SSID:/purple/
    command: /opt/docker-internal.sh 2 100
    depends_on:
      - dev3
              
  dev1:
    container_name: dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2204:22"
    hostname: dev1
    volumes:
      - /home/nate/SSID:/purple/
    command: /opt/docker-internal.sh 2 100
    depends_on:
      - dev2
              
