version: '3'
services:
  dev1:
    container_name: dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2201:22
    hostname: dev1
    volumes:
      - /home/amc1100/Documents/research/SSID:/purple/
              
  dev2:
    container_name: dev2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2202:22
    hostname: dev2
    volumes:
      - /home/amc1100/Documents/research/SSID:/purple/
    depends_on:
      - dev1
              
  dev3:
    container_name: dev3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2203:22
    hostname: dev3
    volumes:
      - /home/amc1100/Documents/research/SSID:/purple/
    depends_on:
      - dev2
              
  dev4:
    container_name: dev4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2204:22
    hostname: dev4
    volumes:
      - /home/amc1100/Documents/research/SSID:/purple/
    depends_on:
      - dev3
              
