FROM ubuntu
# UNUSED CURRENTLY
# --------Dockerfile: Host4
RUN apt update && apt install openssh-server sudo python3 sshpass tcpdump vim tmux tmuxinator netcat pip docker net-tools -y

# ---------user configuration
RUN echo 'root:password' | chpasswd
RUN passwd -d root


# --------ssh session configuration
EXPOSE 22
RUN service ssh start
RUN mkdir ~/.ssh
RUN chmod 700 ~/.ssh
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
RUN sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/g' /etc/ssh/sshd_config
RUN echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config
RUN touch ~/.ssh/authorized_keys
COPY config /root/.ssh/
RUN chmod 600 ~/.ssh/config
RUN service ssh restart


# --------docker-external.sh 
COPY tmux.sh /usr/local/sbin/
RUN chmod +x /usr/local/sbin/tmux.sh
COPY docker-internal.sh /usr/local/sbin/
RUN chmod +x /usr/local/sbin/docker-internal.sh
CMD ["/usr/local/sbin/docker-internal.sh"]

# --------alias building
# RUN echo 'alias hi="echo hello"' >> ~/.bashrc
