version: '3'
services:
  dev5:
    container_name: dev5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2205:22"
      - "9995:9000"
    hostname: dev5
    volumes:
      - ${SHARED_VOLUME}:/purple/
    command: /opt/docker-internal.sh ${SCAN_TIME}
    stdin_open: true
    tty: true
              
  dev4:
    container_name: dev4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2204:22"
      - "9994:9000"
    hostname: dev4
    volumes:
      - ${SHARED_VOLUME}:/purple/
    command: /opt/docker-internal.sh ${SCAN_TIME}
    depends_on:
      - dev5
    stdin_open: true
    tty: true
              
  dev3:
    container_name: dev3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2203:22"
      - "9993:9000"
    hostname: dev3
    volumes:
      - ${SHARED_VOLUME}:/purple/
    command: /opt/docker-internal.sh ${SCAN_TIME}
    depends_on:
      - dev4
    stdin_open: true
    tty: true
              
  dev2:
    container_name: dev2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2202:22"
      - "9992:9000"
    hostname: dev2
    volumes:
      - ${SHARED_VOLUME}:/purple/
    command: /opt/docker-internal.sh ${SCAN_TIME}
    depends_on:
      - dev3
    stdin_open: true
    tty: true
              
  dev1:
    container_name: dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2201:22"
      - "9991:9000"
    hostname: dev1
    volumes:
      - ${SHARED_VOLUME}:/purple/
    command: /opt/docker-internal.sh ${SCAN_TIME}
    depends_on:
      - dev2
    stdin_open: true
    tty: true
              
networks:
  default:
      name: SSID1
      external: true
